{% set name = "asyncache" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/asyncache-{{ version }}.tar.gz
  sha256: 9a1e60a75668e794657489bdea6540ee7e3259c483517b934670db7600bf5035

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core
  run:
    - python >={{ python_min }},<4.0
    - cachetools >=5.2.0,<6.0.0

test:
  imports:
    - asyncache
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/hephex/asyncache
  summary: Helpers to use cachetools with async code.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
